### ISSUE TITLE
libstdcc++ error - -ldylib1.o not found - error when creating tweaks after installing xcode 8 and new mac os sierra

### ISSUE THREAD

**Issue by kallism** [roodkcab/theos-jailed#2]
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
ld: library not found for -ldylib1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [obj/oldnbatest.dylib.855abb9a.unsigned] Error 1
make[1]: **\* [internal-library-all_] Error 2

**Comment by shuoshi** [comment]
take a look at "makefiles/targets/Darwin/iphone.mk", make sure _THEOS_TARGET_IPHONEOS_DEPLOYMENT_VERSION is 7.0

**Comment by kallism** [comment]
@roodkcab Could not find_THEOS_TARGET_IPHONEOS_DEPLOYMENT_VERSION  in the file.. could you amend the file and upload it please if you dont mind? Thanks a lot !

**Comment by roodkcab** [comment]
@kallism take a look at [issue 3](https://github.com/roodkcab/theos-jailed/issues/3)
