### ISSUE TITLE
Theos jailed not working with new xcode

### ISSUE THREAD

**Issue by ifonefreak** [roodkcab/theos-jailed#3]
Could you please update theos jailed to make it work with new xcode? Thanks

**Comment by roodkcab** [comment]
can u give me more detail of the error you encountered? is there any log? I've tested on the latest XCode 8.2.1, and everything is alright.

**Comment by ifonefreak** [comment]
Well, it says something about moving to libc++ , how can I do that? 


clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7
ld: library not found for -ldylib1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [obj/mytweak12.dylib.855abb9a.unsigned] Error 1
make[1]: *** [internal-library-all_] Error 2

**Comment by ifonefreak** [comment]
How can I modify this:

_THEOS_TARGET_IPHONEOS_DEPLOYMENT_VERSION  to version 7. I could not find any number so as to change it in the iphone.mk file within darwin folder. Please help out please

**Comment by ifonefreak** [comment]
Thanks a lot for the reply !! Issue Resolved !! 👍  Thanks again :)
