### ISSUE TITLE
Possible add cycript for 64 bit ?

### ISSUE THREAD

**Issue by vohulg** [roodkcab/theos-jailed#4]
Is it possible add cycript for 64 bit ?

**Comment by roodkcab** [comment]
No problem. @vohulg take a look at the example project [here](https://github.com/roodkcab/safaribooks-exporter) I added a jspatch.framework, to inject javascript code to SafaribooksOnline. u just need to compile a 64bit framework of cycript, and link with it in Makefile.

**Comment by vohulg** [comment]
Thank's i try
