### ISSUE TITLE
Can't correct patch WhatsApp.ipa

### ISSUE THREAD

**Issue by vohulg** [roodkcab/theos-jailed#5]
Hi. I try to use your project for patching WhatsApp ipa. I created ad hoc provision profile for patching, put this provision profile file to WhatsApp.ipa befor patching by name embedded.mobileprovision, then compiled test.dylib for patching and run " `./patchapp patch  WhatsApp.ipa  /path/to/embedded.mobileprovision`". Then install embedded.mobileprovision file to device with Xcode. Then try install patched ipa to device, but patched application can't deploy to device - i have error `A valid provisioning profile for this executable was not found`.

Are you know why problem ? Have you try patch with your project Whatsapp.ipa with ad-hoc provision profile ?

WhatsApp ipa for patching i use in this [link](http://dl.asfadel.kz/WhatsApp_Messenger_2.16.20.10.ipa) -

**Comment by roodkcab** [comment]
Sorry for replying late. I think u have to resign the IPA with new id bind to your afhoc provisioning profile first. U can use iResign or xcode to do the job, good luck
